export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const RESET_RESTAURANTS = 'RESET_RESTAURANTS';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
